### ISSUE TITLE
xz 指令的路徑

### ISSUE THREAD

**Issue by sati-bodhi** [kuanyui/moedict.el#2]
安裝時萌典說系統上沒有發現`xz`指令。但系統上明明有。
```
$ which xz
/usr/local/bin/xz
```
如何讓萌典知道`xz`指令的路徑？

**Comment by kuanyui** [comment]
哇好驚訝竟然有人在用！

通常這都是 PATH 的問題（我猜你用 macOS + Homebrew？），你可以考慮兩種方法：
1. 自己修改 Emacs 內 PATH 的值
2. 直接在 Emacs 設定檔內摳這個讓他自動幫你設定 PATH https://github.com/purcell/exec-path-from-shell

詳情可以參考我的 .emacs.d https://github.com/kuanyui/.emacs.d/blob/master/rc/rc-basic.el#L37-L44

**Comment by kuanyui** [comment]
@sati-bodhi Is this issue solved?

**Comment by sati-bodhi** [comment]
對啊，我是用 macOs+Homebrew。我後來用 `exec-path-from-shell` 解決了。謝謝！

**Comment by sati-bodhi** [comment]
請問有辦法讓他可以用 `regex` 或至少是 `wildcard` 來做搜尋嗎？（可以的話我再 open 一個 issue。）謝謝！

**Comment by kuanyui** [comment]
Reopen please. Query is achieved via SQL, so I think it's possible.

**Comment by sati-bodhi** [comment]
Reopen this? Or start a new one?  They are not the same issues.

**Comment by kuanyui** [comment]
Sorry for my fat finger. Open a new issue.
