### ISSUE TITLE
Enable Regex or Wildcard search in Moedict

### ISSUE THREAD

**Issue by sati-bodhi** [kuanyui/moedict.el#3]
Can there be a regex or wildcard search function for the dict? Thanks!

**Comment by kuanyui** [comment]
Hmm, I'll take a look

**Comment by kuanyui** [comment]
It is impossible to do with `esqlite`.

Because SQLite itself doesn't implement REGEXP keyword, instead, it's just a preserved C API which let developer to implement it.
https://www.sqlite.org/lang_expr.html

If you need to search in RegExp, please consider open http://www.moedict.org/
