### ISSUE TITLE
Fix issues to make this package up-to-date.

### ISSUE THREAD

**Issue by firmart** [kuanyui/moedict.el#4]
Hi, 
I have no luck to make this package works due to some `helm` issues. Unfortunately, I'm not familiar to `helm` as an `ivy` user. I fixed three little bugs so far, in chronological order:
1. `helm-update: Wrong type argument: number-or-marker-p, t` which I fixed by making the helm arguments a plist.
2. [Invalid function helm-build-sync-source ](https://github.com/alphapapa/org-ql/issues/60) which I fixed as [here](https://github.com/alphapapa/org-ql/commit/d7fe019d6ac212da50916f51f642fdf3de24d2d8).
3. I was unable to use the dictionary (`esqlite--error: esqlite: "near line 1: file is not a database"`), because it was not uncompressed actually. This is due to a typo which downloads the compressed database as `dict.sqlite3` instead of `dict.sqlite3.xz`.

Now, I'm facing this issue after calling `M-x moedict`:

```
Debugger entered--Lisp error: (invalid-slot-name "#<helm-source-sync helm-source-sync-1561d0b6b85a>" (:candidates (lambda nil ("覼" "畧" "玍" "玍七馬八" "玍古" "玍雜子" "槅" "槅子" "槅子眼" "裓" "个" "匄" "皐" "槹" "𢬵" "篼" "篼子" "謌" "槩" "㹠" "瓓" "瓓玕" "駞" "槖" "綉" "鸜" "螠" "厓" "厓山" "厓谷" "鮋" "檿" "魭" "魭斷" "猨" "咏" "伃" "蝆" "叶" "鋣" "鞵" "皷" "疒" "妸" "鞲" "耈" "耉" "苷" "秆" "擀" ...)) :volatile t :candidate-number-limit 200 :action moedict-lookup-and-show-in-buffer :requires-pattern t))
```
Could you take a look to make this package usable again ? 

Thanks!

**Comment by firmart** [comment]
My PR just makes me progress three steps  forward in the debug process. 
I'm still facing the issue I described above
```lisp
Debugger entered--Lisp error: (invalid-slot-name "#<helm-source-sync helm-source-sync-1561d0b6b85a>" (:candidates (lambda nil ("覼" "畧" "玍" "玍七馬八" "玍古" "玍雜子" "槅" "槅子" "槅子眼" "裓" "个" "匄" "皐" "槹" "𢬵" "篼" "篼子" "謌" "槩" "㹠" "瓓" "瓓玕" "駞" "槖" "綉" "鸜" "螠" "厓" "厓山" "厓谷" "鮋" "檿" "魭" "魭斷" "猨" "咏" "伃" "蝆" "叶" "鋣" "鞵" "皷" "疒" "妸" "鞲" "耈" "耉" "苷" "秆" "擀" ...)) :volatile t :candidate-number-limit 200 :action moedict-lookup-and-show-in-buffer :requires-pattern t))
```
BTW, 
- emacs version: 28.0.50 (2021-01-20)
- helm version: 3.6.2 (2021-02-23)

As this package requires only `helm` version 1.9.1, *i.e.* two major versions behind, there are surely some changed machinery.

Could you reopen this issue, as it is still not solved ?

**Comment by kuanyui** [comment]
I didn't close this issue... Seems github closed it automatically when merging a metioned PR....

I have no time to see this today, I don't s please wait or you can also fork and PR.

**Comment by firmart** [comment]
> I didn't close this issue... Seems github closed it automatically when merging a metioned PR....
No worry, github see the keyword "fix" in my PR and auto-close it.

> I have no time to see this today, I don't s please wait or you can also fork and PR.
It's fine, I was just curious about this package and was unable to debug
furthermore with my limited knowledge of helm. 

Thanks!

**Comment by kuanyui** [comment]
Done. Seems to be a bug of Helm.

**Comment by firmart** [comment]
It works now, many thanks!
