### ISSUE TITLE
README: add installation snippet with quelpa-use-package 

### ISSUE THREAD

**Issue by firmart** [kuanyui/moedict.el#6]
This package is not on MELPA. So it would be useful to track it on github using `quelpa`, or as follows, using [quelpa-use-package](https://github.com/quelpa/quelpa-use-package).

```lisp
(use-package moedict
  :quelpa (moedict :fetcher github :repo "kuanyui/moedict.el")
  :ensure t)
```

**Comment by kuanyui** [comment]
I don't know what this is? If you feel it is necessary, please make a PR, thanks.

**Comment by firmart** [comment]
It's like use-package, but you can install package from other place than
ELPA & MELPA, for instance in this specific case, from github. That
simply help to avoid the manual installation step and also help to keep
the package up-to-date from its source.
